/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CreateContactResponseData extends SpeakeasyBase {
    /**
     * address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * city.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    /**
     * country.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    /**
     * fullName.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fullName" })
    fullName?: string;

    /**
     * gender.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gender" })
    gender?: string;

    /**
     * phone.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: string;

    /**
     * state.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "state" })
    state?: string;

    /**
     * zipcode.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "zipcode" })
    zipcode?: string;
}

export class CreateContactResponse extends SpeakeasyBase {
    /**
     * Status code of the request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => CreateContactResponseData)
    data?: CreateContactResponseData;

    /**
     * Response description.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * Response
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
