/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateContactRequest extends SpeakeasyBase {
    /**
     * status of your group.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;
}
