/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateTagRequest extends SpeakeasyBase {
    /**
     * Update your tag.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tag_name" })
    tagName: string;
}
