/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdateGroupResponseData extends SpeakeasyBase {
    /**
     * Updated group ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "group_id" })
    groupId?: string;

    /**
     * Updated group name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "group_name" })
    groupName?: string;
}

export class UpdateGroupResponse extends SpeakeasyBase {
    /**
     * Status code of the request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => UpdateGroupResponseData)
    data?: UpdateGroupResponseData;

    /**
     * Response description.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * Response
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
