/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdateContactResponseData extends SpeakeasyBase {
    /**
     * Updated contact ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contact_id" })
    contactId?: number;

    /**
     * Updated group ID.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "group_id" })
    groupId?: string;

    /**
     * Response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class UpdateContactResponse extends SpeakeasyBase {
    /**
     * Status code of the request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => UpdateContactResponseData)
    data?: UpdateContactResponseData;

    /**
     * Response description.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    /**
     * Response
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
